export default {

  // login
  REQUEST_INITIATE: 'REQUEST_INITIATE',
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOG_OUT: 'LOG_OUT',

  STATUS_SUCCESS: 'STATUS_SUCCESS',
  STATUS_FAIL: 'STATUS_FAIL',
};

