const fieldName = {
  AddAdmin: {
    emiratesId: 'National Identity No',
    userRole: 'User Role',
    fullName: 'Full Name',
    // 'lastName': 'Last Name',
    // 'password': 'Password',
    address: 'Address',
    city: 'City',
    country: 'Country',
    nationlaity: 'Nationality',
    dateOfBirth: 'Date of Birth',
    contactNumber: 'Contact Number',
    emailAddress: 'Email Address',
    emergencyName: 'Emergency Contact Name',
    relation: 'Relation',
    emergencyNumber: 'Emergency Contact Number',
  },
  EditAdmin: {
    emiratesId: 'National Identity No',
    // 'userRole': 'User Role',
    name: 'Full Name',
    // 'password': 'Password',
    // 'address': 'Address',
    city: 'City',
    country: 'Country',
    nationality: 'Nationality',
    dateOfBirth: 'Date of Birth',
    phoneNumber: 'Contact Number',
    email: 'Email Address',
    emergencyName: 'Emergency Contact Name',
    emergencyRelation: 'Relation',
    emergencyNumber: 'Emergency Contact Number',
  },
  AddHotel: {
    hotelName: 'Hotel Name',
    bookingLimit: 'Booking Limit',
    hotelAddress: 'Address',
    hotelAddressLat: 'Latitude',
    hotelAddressLong: 'Longitude',
    emiratesId: 'National Identity No',
    fullName: 'Full Name',
    password: 'Password',
    homeAddress: 'User Address',
    city: 'City',
    country: 'Country',
    nationlaity: 'Nationality',
    dateOfBirth: 'Date of Birth',
    contactNumber: 'Contact Number',
    emailAddress: 'Email Address',
    relation: 'Relation',
    emergencyNumber: 'Emergency Contact Number',
    emergencyName: 'Emergency Contact Name',
  },
  EditHotel: {
    hotelName: 'Hotel Name',
    bookingLimit: 'Booking Limit',
    latitude: 'Latitude',
    longitude: 'Longitude',
    emiratesId: 'National Identity No',
    name: 'Full Name',
    homeAddress: 'User Address',
    city: 'City',
    country: 'Country',
    nationality: 'Nationality',
    phoneNumber: 'Contact Number',
    email: 'Email Address',
    emergencyRelation: 'Relation',
    emergencyNumber: 'Emergency Contact Number',
    emergencyName: 'Emergency Contact Name',
  },
  AddBooking:
    { // Add bookings
      guestName: 'Guest Name',
      contactNumber: 'Contact Number',
      emailAddress: 'Email Address',
      // 'passportNumber': 'Passport Number',
      country: 'Country',
      flightNumber: 'Flight Number',
      flightDate: 'Flight Date',
      flightTime: 'Flight Time',
      // 'pickupDate': 'Pickup Date',
      pickupTime: 'Pickup Time',
      pickupAddress: 'Address',
      flatOfficeNumber: 'Flat / Office #',
      floorNumber: 'Floor No.',
      luggages: 'Luggages',
      dropoffAirport: 'Dropoff Airport',
      dropoffTerminal: 'Dropoff Terminal',
      // 'dropoffDate': 'Dropoff Date',
      dropoffTime: 'Dropoff Time',
      // 'pickupLong': 'Please select near landmark from map',
      pickupLat: 'Please select near landmark from map',
      numberOfCompanions: 'numberOfCompanions',
      description: 'description',
      commentsForDriporter: 'commentsForDriporter',
    },
  EditBooking: {
    // 'guestName': 'Guest Name',
    // 'contactNumber': 'Contact Number',
    // 'emailAddress': 'Email Address',
    // 'passportNumber': 'Passport Number',
    // 'nationality': 'Nationality',
    // 'flightNumber': 'Flight Number',
    // 'flightDate': 'Flight Date',
    // 'flightTime': 'Flight Time',
    // 'pickupDate': 'Pickup Date',
    // 'pickupTime': 'Pickup Time',
    // 'pickupAddress': 'Address',
    // 'flatOfficeNumber': 'Flat / Office #',
    // 'floorNumber': 'Floor No.',
    numberOfBags: 'Luggages',
    // 'dropoffAirport': 'Airport',
    // 'dropoffTerminal': 'Terminal',
    // 'dropoffDate': 'Date',
    // 'dropoffTime': 'Time'
  },
  AddOpsporter:
    { // Add opsporter
      name: 'Full Name',
      phoneNumber: 'Contact Number',
      email: 'Email Address',
      // 'maritalStatus': 'Marital Status',
      city: 'City',
      nationality: 'Nationality',
      passportNumber: 'Passport Number',
      // 'passportCountry': 'Passpord Country',
      passportValidity: 'Passport Validty',
      visaNumber: 'Visa Number',
      visaValidity: 'Visa Validity',
      emiratesId: 'National Identity No',
      homeAddress: 'Home Town Address',
      emergencyName: 'Emergency Contact Person',
      emergencyNumber: 'Emergency Contact Number',
      emergencyRelation: 'Relation',
      maritalStatus: 'Marital Status',
      profilePicture: 'Profile Picture',
      passportImage: 'Passport',
      visaImage: 'Visa',
      // 'drivingLicense': 'Driving License',
      workPermit: 'Work Permit',
      airportId: 'Airport',
      dateOfBirth: 'Date of Birth',

    },
  EditOpsporter:
    { // Edit opsporter
      name: 'Full Name',
      phoneNumber: 'Contact Number',
      email: 'Email Address',
      maritalStatus: 'Marital Status',
      city: 'City',
      // 'homeAddress': 'Home Address',
      nationality: 'Nationality',
      passportNumber: 'Passport Number',
      // 'passportCountry': 'Passpord Country',
      // 'passportValidity': 'Passport Validty',
      visaNumber: 'Visa Number',
      // 'visaValidity': 'Visa Validity',
      emiratesId: 'National Identity No',
      emergencyName: 'Emergency Contact Person',
      emergencyNumber: 'Emergency Contact Number',
      emergencyRelation: 'Relation',
      // 'profilePicture': 'Profile Picture',
      // 'passportImage': 'Passport',
      // 'dateOfBirth': 'Date of Birth',
      // 'visaImage': 'Visa Image',
      // 'drivingLicense': 'Driving License',
      // 'airPortId': 'Airport'
    },
  AddDriporter:
    { // Add opsporter
      name: 'Full Name',
      phoneNumber: 'Contact Number',
      email: 'Email Address',
      // 'maritalStatus': 'Marital Status',
      city: 'City',
      nationality: 'Nationality',
      passportNumber: 'Passport Number',
      // 'passportCountry': 'Passpord Country',
      passportValidity: 'Passport Validty',
      visaNumber: 'Visa Number',
      visaValidity: 'Visa Validity',
      emiratesId: 'National Identity No',
      homeAddress: 'Home Town Address',
      emergencyName: 'Emergency Contact Person',
      emergencyNumber: 'Emergency Contact Number',
      emergencyRelation: 'Relation',
      maritalStatus: 'Marital Status',
      profilePicture: 'Profile Picture',
      passportImage: 'Passport',
      visaImage: 'Visa',
      // 'drivingLicense': 'Driving License',
      workPermit: 'Work Permit',
      serviceAreaId: 'Service Area',
      dateOfBirth: 'Date of Birth',

    },
  EditDriporter:
    { // Edit opsporter
      name: 'Full Name',
      phoneNumber: 'Contact Number',
      email: 'Email Address',
      maritalStatus: 'Marital Status',
      city: 'City',
      // 'homeAddress': 'Home Address',
      nationality: 'Nationality',
      passportNumber: 'Passport Number',
      // 'passportCountry': 'Passpord Country',
      // 'passportValidity': 'Passport Validty',
      visaNumber: 'Visa Number',
      // 'visaValidity': 'Visa Validity',
      emiratesId: 'National Identity No',
      emergencyName: 'Emergency Contact Person',
      emergencyNumber: 'Emergency Contact Number',
      emergencyRelation: 'Relation',
      // 'profilePicture': 'Profile Picture',
      // 'passportImage': 'Passport',
      // 'dateOfBirth': 'Date of Birth',
      // 'visaImage': 'Visa Image',
      // 'drivingLicense': 'Driving License',
      // 'serviceAreaId': 'Service Area'
    },
  AddHotelBooking: {
    guestName: 'Guest Name',
    contactNumber: 'Contact Number',
    emailAddress: 'Email Address',
    // 'passportNumber': 'Passport Number',
    country: 'Country',
    flightNumber: 'Flight Number',
    flightDate: 'Flight Date',
    flightTime: 'Flight Time',
    // 'pickupDate': 'Pickup Date',
    pickupTime: 'Pickup Time',
    // 'pickupAddress': 'Address',
    flatOfficeNumber: 'Room #',
    floorNumber: 'Floor No.',
    luggages: 'Luggages',
    dropoffAirport: 'Airport',
    dropoffTerminal: 'Terminal',
    // 'dropoffDate': 'Date',
    dropoffTime: 'Time',
    // 'pickupLong': 'Longitude',
    // 'pickupLat': 'Latitude'
  },
  EditHotelBooking: {
    // 'guestName': 'Guest Name',
    // 'contactNumber': 'Contact Number',
    // 'emailAddress': 'Email Address',
    // 'passportNumber': 'Passport Number',
    // 'nationality': 'Nationality',
    // 'flightNumber': 'Flight Number',
    // 'flightDate': 'Flight Date',
    // 'flightTime': 'Flight Time',
    // 'pickupDate': 'Pickup Date',
    // 'pickupTime': 'Pickup Time',
    // 'pickupAddress': 'Address',
    // 'flatOfficeNumber': 'Flat / Office #',
    // 'floorNumber': 'Floor No.',
    numberOfBags: 'Luggages',
    // 'dropoffAirport': 'Airport',
    // 'dropoffTerminal': 'Terminal',
    // 'dropoffDate': 'Date',
    // 'dropoffTime': 'Time'
  },
  AddHotelStaff:
    {
      name: 'Full Name',
      phoneNumber: 'Contact Number',
      email: 'Email Address',
      // 'maritalStatus': 'Marital Status',
      city: 'City',
      nationality: 'Nationality',
      // 'passportNumber': 'Passport Number',
      // 'passportCountry': 'Passpord Country',
      // 'passportValidity': 'Passport Validty',
      // 'visaNumber': 'Visa Number',
      // 'visaValidity': 'Visa Validity',
      emiratesId: 'National Identity No',
      homeAddress: 'Home Town Address',
      emergencyName: 'Emergency Contact Person',
      emergencyNumber: 'Emergency Contact Number',
      emergencyRelation: 'Relation',
      // 'maritalStatus': 'Marital Status',
      profilePicture: 'Profile Picture',
      // 'passportImage': 'Passport',
      // 'visaImage': 'Visa',
      // 'drivingLicense': 'Driving License',
      // 'workPermit': 'Work Permit',
      // 'airportId': 'Airport',
      dateOfBirth: 'Date of Birth',

    },
  EditHotelStaff: {
    name: 'Full Name',
    phoneNumber: 'Contact Number',
    email: 'Email Address',
    city: 'City',
    nationality: 'Nationality',
    emiratesId: 'National Identity No',
    homeAddrress: 'Home Town Address',
    emergencyName: 'Emergency Contact Person',
    emergencyNumber: 'Emergency Contact Number',
    emergencyRelation: 'Relation',
    // 'maritalStatus': 'Marital Status',
    displayImage: 'Profile Picture',
    // 'dateOfBirth': 'Date of Birth'

  },
  AddVehicle: {
    model: 'Model',
    type: 'Type',
    engineNumber: 'Enginer Number',
    // capacity: 'Capacity',
    chassisNumber: 'Chassis Number',
    insuranceNumber: 'Insurance Number',
    engineType: 'Engine Type',
    registrationNumber: 'Registration Number',
    colour: 'Color',
    numberPlate: 'Number Plate',
    loadCapacity: 'Load Capacity',
    insuranceExpiry: 'Insurance Expiry',
    carImageUrl: 'Vehicle Image',
    leftSideImageUrl: 'Vehicle Left Image',
    rightSideImageUrl: 'Vehicle Right Image',
    engineSideImageUrl: 'Engine Image',
    backSideImageUrl: 'Vehicle Back Image',
  },
  EditVehicle: {
    model: 'Model',
    type: 'Type',
    engineNumber: 'Enginer Number',
    chassisNumber: 'Chassis Number',
    insuranceNumber: 'Insurance Number',
    engineType: 'Engine Type',
    registrationNumber: 'Registration Number',
    colour: 'Color',
    numberPlate: 'Number Plate',
    loadCapacity: 'Load Capacity',
    insuranceExpiry: 'Insurance Expiry',
    carImageUrl: 'Vehicle Image',
    leftSideImageUrl: 'Vehicle Left Image',
    rightSideImageUrl: 'Vehicle Right Image',
    engineSideImageUrl: 'Engine Image',
    backSideImageUrl: 'Vehicle Back Image',
  },
};

const optionalFieldName = {
  AddBooking: ['flatOfficeNumber', 'floorNumber', 'numberOfCompanions', 'description', 'commentsForDriporter'],
};

export const allOptionalInput = ['flatOfficeNumber', 'floorNumber', 'numberOfCompanions', 'description', 'commentsForDriporter'];

export const getfieldsName = formName => fieldName[formName];

export const getOptionalFieldsName = formName => optionalFieldName[formName];

export const getAllOptionalInput = () => allOptionalInput;
